
type ContentType = 'email' | 'report';
type Tone = 'formal' | 'casual' | 'professional' | 'friendly' | 'urgent';

interface GenerateContentParams {
  contentType: ContentType;
  tone: Tone;
  subject: string;
  recipient: string;
  bulletPoints: string;
}

export const generateEmail = (points: string[], tone: Tone, subject: string, recipient: string): string => {
  const greetings = {
    formal: 'Dear',
    casual: 'Hi',
    professional: 'Dear',
    friendly: 'Hello',
    urgent: 'Dear'
  };

  const closings = {
    formal: 'Sincerely',
    casual: 'Best',
    professional: 'Best regards',
    friendly: 'Warm regards',
    urgent: 'Urgently'
  };

  const introLines = {
    formal: 'I hope this email finds you well. I am writing to inform you about the following matters:',
    casual: 'Hope you\'re doing well! I wanted to update you on a few things:',
    professional: 'I hope this message finds you well. I would like to provide you with an update on the following items:',
    friendly: 'I hope you\'re having a great day! I wanted to share some updates with you:',
    urgent: 'I am writing to bring to your immediate attention the following critical matters:'
  };

  return `Subject: ${subject || 'Important Update'}

${greetings[tone]} ${recipient || '[Recipient Name]'},

${introLines[tone]}

${points.map(point => `• ${point.trim()}`).join('\n')}

Please let me know if you have any questions or need further clarification on any of these points.

${closings[tone]},
[Your Name]`;
};

export const generateReport = (points: string[], tone: Tone, title: string): string => {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  const introLines = {
    formal: 'This report presents a comprehensive overview of the following key points and findings:',
    casual: 'Here\'s a quick rundown of the main points covered:',
    professional: 'This document outlines the key findings and important information regarding:',
    friendly: 'This friendly report covers the following important topics:',
    urgent: 'This urgent report highlights critical issues that require immediate attention:'
  };

  return `${title || 'Executive Report'}
Generated on: ${dateStr}

EXECUTIVE SUMMARY
${introLines[tone]}

KEY POINTS:
${points.map((point, index) => `${index + 1}. ${point.trim()}`).join('\n')}

CONCLUSION:
The points outlined above represent the current status and key findings. Further action may be required based on the nature of these items.

---
Report generated by Email & Report Generator`;
};

export const generateContent = (params: GenerateContentParams): string => {
  const points = params.bulletPoints.split('\n').filter(point => point.trim());
  
  if (params.contentType === 'email') {
    return generateEmail(points, params.tone, params.subject, params.recipient);
  } else {
    return generateReport(points, params.tone, params.subject);
  }
};
